language: node_js
node_js:
- 5
cache:
  directories:
  - node_modules
deploy:
  provider: npm
  email: me@mikakalathil.ca
  on:
    tags: true
  api_key:
    secure: RRxupV3hWT+xRSgW9K9l3hc/19PXVmQCr/00TYqQMn3Xy15jnOxid9AzWvYRXniAnM0lfEFbP0GaWDJUMFxAMyb3TROtP8ReUIIpTkB5mznHAvsmsqGWVUiRwc4vU8g3kfuW+xVYQY4OScRNl4OCE3py9usieRm9VhU9dH+oTk9bQKw1IOK+0LdRqo8U83y7VaycTCh2RTOJF73x/2esh4ufp1hVbHnhUCwff6uiwDdL+jthl3wBvXyQC+SMMJllCCwP0/X1HPkFGZ5N2St0K3pyzs/hh9aEdo58ReeGMfPjWT2u+GRw7fwzAD5GGkSDNBvMzzFQ6NVFvcqONCi1L68X5YqByE4OpMqZA7MmNM3jCUpn7wjJnARVNyK5jk3LP7nCBnKwESFAp+Kj0sPEV1gW9CZn905H5y8wN4mCRMqZGJ2y2ljTE0lYIjQH9Nuj81R+GUGpxNGQWDyTwHsYfKMVy4DmDgsAw7nyLAhry6PRqEF4yfeBx49JSrWkfNQlWhH0971HogyoUewk05VDnADNFCuoas3KCe+hJI2pALRbnnKzcQDGJO/MwYrBCW5mCXfNek7zKlTiobM17jhCP9J7V++c0Z1E6dzpU0CBl3IYZJ9Dj5bj/5DC5KwuM5ZnUhAmMgE8LkEZHEip40Iv9NNrZYxNA3Cyupj/+rIc5vk=
